### ISSUE TITLE
pip installed frisk fails to run on mac 

### ISSUE THREAD

**Issue by Adamtaranto** [Adamtaranto/frisk#12]
Tested pip install on Eli's mac. Not sure if this issue stems from the blank frisk version.
```
>>> pip install cython numpy scipy
>>> pip install frisk
>>> frisk -h
Traceback (most recent call last):
  File "/usr/local/bin/frisk", line 9, in <module>
    load_entry_point('frisk==0-unknown', 'console_scripts', 'frisk')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 2184, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/site-packages/frisk/__init__.py", line 19, in <module>
    from hmmlearn import hmm
  File "/usr/local/lib/python2.7/site-packages/hmmlearn/hmm.py", line 15, in <module>
    from sklearn.utils import check_random_state
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 16, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from ..utils.fixes import in1d
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/fixes.py", line 316, in <module>
    from ._scipy_sparse_lsqr_backport import lsqr as sparse_lsqr
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/_scipy_sparse_lsqr_backport.py", line 58, in <module>
    from scipy.sparse.linalg.interface import aslinearoperator
  File "/Library/Python/2.7/site-packages/scipy/sparse/linalg/__init__.py", line 109, in <module>
    from .isolve import *
  File "/Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 7, in <module>
    from . import _iterative
ImportError: dlopen(/Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/_iterative.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin12.5.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/_iterative.so
  Reason: image not found
```

**Comment by kdmurray91** [comment]
Is that in a python shell?

**Comment by kdmurray91** [comment]
And does he have gcc installed? It's missing the fortran library, which is required to run scipy and hence frisk.
Tell him to try:

```python 
>>>  import scipy
```
in a fresh python shell.

**Comment by Adamtaranto** [comment]
regular terminal.

**Comment by Adamtaranto** [comment]
Cool, I'll check that out.

**Comment by kdmurray91** [comment]
```
Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin12.5.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/_iterative.so
```
 is the key bit

**Comment by Adamtaranto** [comment]
fixed with 'pip install --upgrade scipy'
